services:
  nba-player-guesser:
    image: 939365853055.dkr.ecr.us-east-1.amazonaws.com/nba-player-guesser-api:master
    environment:
      - PORT=$PORT
    pull_policy: always
    # build: ./api #for local run
    user: root
    depends_on:
      - redis
    # volumes:
    #   - ~/.aws:/root/.aws #for boto3 to access aws creds locally
    ports:
      # - 8080:8080 # (docker port to open up):(port on app) locally
      - $PORT:$PORT # (docker port to open up):(port on app)
  redis:
    image: redis:7.0.15-alpine
# docker compose creates a virtual network for all containers so by default each container can access all the others defined in the compose file and their host name match their service name
